[versions]
# App SDK
app-compileSdk = "35"
app-minSdk = "24"
app-targetSdk = "35"

# Build tools & Gradle plugins
androidGradlePlugin = "9.0.0"
firebaseCrashlyticsGradle = "3.0.2"
googleServices = "4.4.2"
kotlin = "2.3.10"

# Compose compiler
compose-compiler-version = "1.5.14"

# Compose UI
composeFoundation = "1.7.5"
composeMaterial = "1.7.5"
composeMaterial3 = "1.3.1"
composeUi = "1.7.5"
composeUiTooling = "1.7.5"
materialIconsCore = "1.7.7"
materialIconsExtended = "1.7.7"
uiTestJunit4 = "1.7.7"
uiToolingPreview = "1.7.5"

# AndroidX UI / Views
activityCompose = "1.10.0"
androidxCoreKtx = "1.15.0"
appcompat = "1.7.0"
browser = "1.8.0"
constraintlayout = "2.2.0"
viewpager2 = "1.1.0"

# Lifecycle
lifecycleViewmodelCompose = "2.8.7"

# Navigation
navigationFragmentKtx = "2.8.6"
navigationUiKtx = "2.8.6"

# Kotlin / Coroutines
kotlinxCoroutinesAndroid = "1.7.3"

# Dependency Injection
koinAndroid = "3.4.0"

# Firebase
firebaseBom = "33.5.1"

# Play
playReview = "2.0.2"
playReviewKtx = "2.0.2"

# Images
coilCompose = "2.6.0"

# Material Theme Adapter
composeThemeAdapter = "1.2.1"

# Testing
junit = "4.13.2"

# Logging
timber = "5.0.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-theme-adapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "composeThemeAdapter" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeFoundation" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinAndroid" } # koin-androidにできない？
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigationUiKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
play-review = { module = "com.google.android.play:review", version.ref = "playReview" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "playReviewKtx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-database = {group = "com.google.firebase", name = "firebase-database-ktx"}
firebase-analytics = {group = "com.google.firebase", name = "firebase-analytics-ktx"}
firebase-crashlytics = {group = "com.google.firebase", name = "firebase-crashlytics"}
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
